### ISSUE TITLE
[Feature Request] Unlock Genshin Impact fps limit

### ISSUE THREAD

**Issue by abbaccadd0** [neon-nyan/Collapse#104]
The HI3 settings can be customized in Collapse Launcher, but GI can only customize the launch parameters.
Maybe more options can be added to GI, such as resolution, window mode (full screen, windowed, borderless), [unlocking the frame rate limit](https://github.com/DGP-Studio/Unlocker), or launching another program (like [unlockfps](https://github.com/34736384/genshin-fps-unlock)) to launch GI.
Collapse Launcher is beautiful and convenient, I like it a lot, these are just suggestions, not bugs.
🥰🥰🥰

**Comment by bagusnl** [comment]
Thank you for your interest in Collapse Launcher also for the suggestion!
Settings menu for Genshin Impact (much like what's current Honkai Impact settings page looks like) is a planned feature we want to implement. But, for the FPS Unlock, we unfortunately might not be able to do that since it requires writing directly into GI process memory (different to what HI3 method of just modifying the game settings registry file). This in turns means that it would be a direct violation to [Genshin's Terms of Service](https://genshin.hoyoverse.com/en/company/terms#:~:text=iv.%20Develop%2C%20use%20or%20distribute%20any%20software%2C%20script%20code%2C%20plug%2Din%20unit%2C%20programs%20or%20applications%20that%20may%20cause%20an%20unfair%20competitive%20advantage%3B) point 2b number iv and viii.

With that in mind. Unfortunately, we cannot implement such feature in hope that miHoYo/Cognosphere will not take this project down (similar to what I explained [here](https://github.com/neon-nyan/Collapse/issues/88#issuecomment-1457422037).

We are sorry that we can't implement such feature, though we hope that this won't stop you from supporting this project.
❤️
