### ISSUE TITLE
Adding support for german translation (on crowdin)

### ISSUE THREAD

**Issue by kujou-kju** [neon-nyan/Collapse#130]
Hey, I recently found out about this project and noticed that it doesn't have german support rn.
I'm interested in providing a german translation but I saw that german isn't available in the crowdin project yet.

I've sent a request dm on crowdin but there was no reaction yet, maybe they missed it - so I decited to now try it here.

PS: I already started by adding a de-de.json to my local installation. It works fine. The launcher even automatically gets the image resources in german now nice as seen in the genshin wish bg for phase 2.

![image](https://user-images.githubusercontent.com/23724383/236953135-77c6c338-5b86-44d6-a932-6ea22ca5a6b2.png)

**Comment by kujou-kju** [comment]
I have fun translating stuff but I saw that an other person (#125) is already working on a german translation which has first far more progress and also has at many points by far better wordings then mine so I gonna stop on my work now. But still I would like to see german finally added to crowdin so for current and future translations you can have a better workflow.

**Comment by kujou-kju** [comment]
PS: Sry my english writing skills aren't the best but I do understand it pretty well tho c:
Also I gonna take @DasIschBims's translation and replace it with my local `de-de.json` file so I can use the launcher in german now.

**Comment by bagusnl** [comment]
since DaslschBims already working on it in their own fork, I think we can wait for them.
There are 2 options right now, 
1. Wait for DaslschBims to finish the translation and then merge its PR, or
2. DaslschBims  can give or commit their latest de-DE.json, then we upload them to Crowdin after that both of you can help translating strings to German.
Both of them are valid options, I'll wait for @neon-nyan to pick an option.
Since we also planning to implement HSR Game Settings in the next major version, there will be more strings to translate. Though most of them are copies from HI3 Game Settings locale so it shouldn't take too long.

**Comment by neon-nyan** [comment]
Hi @kujou-kju,
Thank you for your interest on the localization and sorry for my late reply since I don't feel well for a few days recently.
As per information by @bagusnl, we have two choices for both of you to join the latest PR or waiting for us to add Daslsch's latest commit to Crowdin as we just added the language.

But for me, we can have the second option to be applied since both on you could collaborate together on the localization.
I'm now adding the latest commit of the PR to Crowdin.
