### ISSUE TITLE
[Feature Request] Making it easier to go back to launcher page

### ISSUE THREAD

**Issue by kujou-kju** [neon-nyan/Collapse#131]
Currently when you have any other page than the launcher one open (file check/repair/app settings etc) you always have to do it though the "hamburger" menu. I think it should be easier accessable.

I have 3 ideas how this could be implemented:

1. Idea: Making the Collapse Launcher title clickable like logos on websites usually are which goes back to/opens the launcher page
2. Idea: Adding a back button into each page so you can click on it when the settings/repair/file check screens are open
3. Idea: Adding a home or back button into the titlebar itself

**Comment by bagusnl** [comment]
Thank you for your input on how we can implement back-to-home button. We will try to discuss more about this as its quite a nice add-on that will improve QoL for Collapse. The initial discussion we got is that we might be able to use the Collapse logo on the top left as a button to always go to the mainpage, this might change in the future as we try to implement it.
As for when, we still are thinking about it since there are quite a lot of backlog for the next major release but we'll notify this Issue thread once its come into fruition.
Thanks again for your input !

**Comment by Cryotechnic** [comment]
Current preview build (1.71.4) introduces this functionality. Marking as fixed and will close once next mainline release ships. Thanks for the suggestion!

**Comment by bagusnl** [comment]
Closing this as its shipped with the latest Preview
