### ISSUE TITLE
Launcher crashes when trying to pre-download Honkai Star Rail

### ISSUE THREAD

**Issue by seriaati** [neon-nyan/Collapse#158]
![help](https://github.com/neon-nyan/Collapse/assets/61446626/28894c24-3650-483e-8615-12395dd9119d)

**Comment by bagusnl** [comment]
Hello~ thanks for reporting this issue

I'm pretty sure that this issue is another catastrophic from the other one #156 and the fix is underway.
If you would like to test the preload downloading using a test build, you can use this build right here
https://www.mediafire.com/file/13h54rtrckdkmbe/Collapse-Debug_670b93d47783e2b409bdb2bf7bed2345fbd0c949_10.0.19041.0_Net7.0.7z/file
Please keep in mind that this debug build doesn't have any updater so make sure to use normal builds (pre/stable) after you've done with downloading the game.

To use this build, just extract it and run CollapseLauncher.exe, all configs from normal build will be used.

Let us know if you have any difficulties or issues using this build.

We're sorry for the inconvenience

**Comment by seriaati** [comment]
Got it, thank you.
