### ISSUE TITLE
[Bug]: update issue in China.

### ISSUE THREAD

**Issue by Dinnerbonex3rd** [neon-nyan/Collapse#175]
### Affected Version

1.70.6 preview

### Bug Behavior

I can receive the update by DeLivr,but cant download the latest ver.

### Expected Behavior

When I began to download the new ver,It showed downloading but was stuck with 1/1 and 0h 0min 0s,then error occurred as
System.AggregateException: All available CDNs aren't reachable for your network while getting content: preview/ApplyUpdate.exe. Please check your internet!
   at CollapseLauncher.FallbackCDNUtil.DownloadCDNFallbackContent(Http httpInstance, String outputPath, Int32 parallelThread, String relativeURL, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\Classes\RegionManagement\FallbackCDNUtil.cs:line 105
   at CollapseLauncher.Updater.StartLegacyUpdate() in E:\myGit\Collapse\CollapseLauncher\XAMLs\Updater\Classes\Updater.cs:line 142
   at CollapseLauncher.Updater.StartUpdate(UpdateInfo UpdateInfo, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\XAMLs\Updater\Classes\Updater.cs:line 118
   at CollapseLauncher.Pages.UpdatePage.GetSquirrelUpdate() in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\UpdatePage.xaml.cs:line 93
   at CollapseLauncher.Pages.UpdatePage.StartUpdateRoutine() in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\UpdatePage.xaml.cs:line 67

### Steps to reproduce

as above

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/121348180/6a0d503e-3bb8-48c2-8f01-58d709f20d72)

**Comment by Dinnerbonex3rd** [comment]
I can access Bitbucket or GitLab normally in China, and Bitbucket loads faster than GitLab.

**Comment by bagusnl** [comment]
Thank you for the input, we will discuss for a potential fix and will give you an update once a solution is made

**Comment by Scighost** [comment]
@Dinnerbonex3rd You need a proxy server.

**Comment by Cryotechnic** [comment]
> 

Out of curiosity, I saw you using Cloudflare to distribute metadata and updates in your project. Would you say that their R2 bucket storage would remedy this issue? 

It's something we're looking into in general as well, since Cloudflare has a lot more servers and has broader availability than our current providers. We're always looking on making the launcher more accessible to a broader audience, so your input would really help :DD

**Comment by Scighost** [comment]
@Cryotechnic 

Because of the complex network environment in mainland China, it is difficult for users in it to access the international Internet. For example, I'm downloading files from GitHub releases very slowly, and I can't access statically directly at all.

The best solution would be to enable an independent CDN in mainland China, but this is not realistic from either a cost or policy perspective. CloudFlare network nodes are accessible in mainland China, and will rarely be randomly blocked, although the speed of some areas is slow. The most important thing is that it's free!

In addition to that, during the version update of my project, I don't download the entire package, but rather the diff-content files. And brotli compression is also enabled to minimize the amount of data transfer as much as possible.

The following shows the accessibility of some servers in mainland China, these results are made worse during peak network periods or some special times. Gray areas are completely inaccessible.

<details>

**GitHub Blob**

![image](https://github.com/neon-nyan/Collapse/assets/61003590/5dbb22ce-2833-40d0-ae22-03038dadef8e)


**CloudFlare**

![image](https://github.com/neon-nyan/Collapse/assets/61003590/30b40bf1-10f8-4365-af56-883b61013e9a)


**GitHub Release**

![image](https://github.com/neon-nyan/Collapse/assets/61003590/85843aeb-09d8-497f-8c6c-4bc820b0fd6d)

**Statically**

![image](https://github.com/neon-nyan/Collapse/assets/61003590/3eb75c0e-3320-4919-82f2-2876c85a5864)

</details>

**Comment by bagusnl** [comment]
> In addition to that, during the version update of my project, I don't download the entire package, but rather the diff-content files. And brotli compression is also enabled to minimize the amount of data transfer as much as possible.
> @Scighost 
I believe we already do that using Squirell, that's why we have delta (the compressed diff) and full (compressed full package) in our ReleaseRepo. But the problem is that we need to download the ApplyUpdate.exe when it got updated or some other scenarios. Unsure why both jsDelivr and Statically just stopped serving this file for unknown reason.

That is why we are searching for alternative, currently bitbucket seems pretty good but I'm still not sure for its accessibility in China since I've read from some support pages it got blocked/restricted sometimes too.

One question though, how does Cloudflare nodes is implemented in your case?

**Comment by Scighost** [comment]
> Unsure why both jsDelivr and Statically just stopped serving this file for unknown reason.

jsDelivr blocks files with `.exe` extension.
https://github.com/jsdelivr/jsdelivr/issues/18441#issuecomment-1287859070

> One question though, how does Cloudflare nodes is implemented in your case?

I use CloudFlare to proxy an object storage service (equals AWS S3) in Alibaba Cloud.

By the way, you can test network accessibility using this website: https://www.17ce.com

**Comment by bagusnl** [comment]
> By the way, you can test network accessibility using this website: https://www.17ce.com
@Scighost 

Thank you for your insight!
Seems like bitbucket do have problems in certain area as well, but quite promising. We will wait for neon's insight on this and what we should do next knowing all the infos

17ce result for Bitbucket repo mirror
https://www.17ce.com/site/http/20230619_ef66bb600e9411eeac17e316c626d952:1.html
![image](https://github.com/neon-nyan/Collapse/assets/28079733/14257dc7-fe7a-4643-8c52-d331ec645ed2)

**Comment by bagusnl** [comment]
Bitbucket is implemented with commit https://github.com/neon-nyan/Collapse/commit/f516b341fa2881cfe976e80ac18009e71618a153

Note for all affected Collapse users, when the next update for Collapse is announced and the in-app update mechanism fails, please download the update from this repository Releases and then install the new version on top of the old installation. This has to be done because the old version doesn't have necessary methods to use Bitbucket as the mirror for Collapse updates.
