### ISSUE TITLE
[Request] A Switch to Turn Off Acrylic Effects

### ISSUE THREAD

**Issue by djdjz7** [neon-nyan/Collapse#190]
**Is your feature request related to a problem? Please describe.**
I've noticed that Collapse Launcher used a lot of acrylic effects. Although small amount of blur effects make the launcher look nice, the huge amount of effect applied here is making the app feel less responsive.

**Describe the solution you'd like**
Please, optimize the use of the acrylic effects. In my personal opinion, large areas (like settings page) should avoid applying the acrylic effect. Or, as an alternative, please add a switch to turn off the acrylic effect so that the launcher could run better on some low-end devices.

**Comment by bagusnl** [comment]
Hello, thank you for submitting an Enhancement request for our Launcher! Can you help us out fill these information so we can understand your current system better as your enhancement request is about performance of the launcher

### System Information
Please attach a copy of `dxdiag.txt` to this issue so that we can better understand your hardware configuration: "Save all information" (Run > Type `dxdiag` then enter > Save all information > Then Drag & Drop the file to your issue, or attach it through the file selection dialog). 

### Collapse Version:
[Which Collapse version and release branch (stable/preview) you are currently running]

**Comment by djdjz7** [comment]
### System Information
[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/11933397/DxDiag.txt)
### Collapse Verion
1.70.11 Stable

**Comment by bagusnl** [comment]
Thank you for providing the details! We will try and work on improving the launcher responsiveness.

While at it, we also notices both of your GPU drivers to be quite out-of-date. While this is most likely aren't related to your issue, it is advised that you follow your system guide on updating both your Intel UHD and Nvidia MX250 GPU Drivers.

**Comment by djdjz7** [comment]
> Thank you for providing the details! We will try and work on improving the launcher responsiveness.
> 
> While at it, we also notices both of your GPU drivers to be quite out-of-date. While this is most likely aren't related to your issue, it is advised that you follow your system guide on updating both your Intel UHD and Nvidia MX250 GPU Drivers. 

Thanks a lot!  
Actually, updating MX250's driver will make the performance worse. But I'll try updating Intel's later.

**Comment by neon-nyan** [comment]
Hi there,

We have been working on a setting to toggle this acrylic effects in the latest PR: #213. The feature is expected to be shipped in the next release.

**Comment by djdjz7** [comment]
Tried the latest version, works great!

thanks for your work!
