### ISSUE TITLE
[Feature Request] Add P2P (torrent) download option

### ISSUE THREAD

**Issue by QPUNeptune** [neon-nyan/Collapse#192]
I dont know how complicated it is to do this, but imma give it a shot anyway. I have no idea if i was tried or if someone requested it.
I had this thought when i remembered that the War Thunder had this.

The way this works is pretty much as a torrent client (what a shocker), but just for delivering the games' files.
Note that this option is TO HELP the download that is already doing, not to replace it. An example: assuming the normal download speed is 5MiB/s, enabling the P2P, which adds 2.5MiB/s in this case, would have the download speed theoretically reach 7.5MiB/s (again, this is an example). 

By adding this option, i reckon that it could improve the download speed of the games. Of course it also needs a way to disable it, some people doesnt want it.

Anyway its more like a suggestion, and sorry for the bad english.

**Comment by MiniGrayGay** [comment]
直接多线程下就已经挺快了？起码能跑到70多M，感觉也够用了吧

**Comment by Cryotechnic** [comment]
Heyo, thanks for your suggestion! While we think it's a great idea, there are a number of risks involved with the proposal, notably:

- We would have no control over the files shared in P2P. This means that a malicious actor could potentially modify game files and put people's systems at risk.
- The game data files are subject to miHoYo/Cognosphere Ltd's copyright, and as such, we believe that there is an increased risk of getting a C&D from them due to the "illegal" distribution of official game data. Furthermore, as per our [Contributing Guidelines](https://github.com/neon-nyan/Collapse/blob/main/CONTRIBUTING.md), we are not planning on implementing features which violate the Terms of Service of any game currently in live operation by miHoYo/Cognosphere Ltd. We encourage you to read the Terms of Service of each title to get a better understanding of the rules by which we are bound.
- Even if we would have implemented this feature, the current tested maximum game data download speed that we know of as developers is around the 100MB/s mark. This means that, while a P2P solution *could*, in theory accelerate download speed, in practice, it would depend on the number of peers (hosts/machines) that actively seed the game data package. There is also the added argument that, knowing that we can download the game's data at a rate of 100MB/s, there is little advantage in trying to squeeze out an extra 2.5MiB/s, especially because of the points listed above. 

War Thunder's situation uses a different method of downloading their game data package. We opted with the safer, direct download approach. That's not to say that P2P is a bad way of doing it; it's just not ideal in our case because of the risks involved with integrating such a solution. Hopefully that clears things up!

**Comment by QPUNeptune** [comment]
Ah no problem, thank for clarifying!
