### ISSUE TITLE
[Request] Allow partial usage of "Quick Settings" functionality while game is open 

### ISSUE THREAD

**Issue by SinsOfSeven** [neon-nyan/Collapse#197]
**Is your feature request related to a problem? Please describe.**
While I'm playing, I find it convenient to have quick access to the screenshots folder and sometimes the game directory.

Unfortunately the Quick Settings menu with these shortcuts is disabled while playing, because the menu has other options for Repairing, Uninstalling Etc.

**Describe the solution you'd like**
Simply re-enable the menu and Disable/Hide the sub options while the game is running.

**Describe alternatives you've considered**
Move these shortcuts to some other part of the launcher, though that seems less practical.

**Additional context**
Keep the red stuff disabled or hidden while game is running.
![image](https://github.com/neon-nyan/Collapse/assets/26401302/ac8e153d-7dd5-487b-8ffa-a3be222b1e4d)

**Comment by bagusnl** [comment]
With commit https://github.com/neon-nyan/Collapse/commit/a73d70880b0342cafbc4f039f0d561e4e3e5d542, Collapse now should only disable game settings related quick settings instead of everything. Thank you for the suggestion!
![image](https://github.com/neon-nyan/Collapse/assets/28079733/9951a759-2e1a-4c23-a09d-d99c733147b7)
We'll close this issue once a release with this commit is up

**Comment by bagusnl** [comment]
as said, release with commit needed is up on preview, so we'll close this issue
Thank you for using Collapse and sending enhancement ideas!
