### ISSUE TITLE
[Bug] Unable to access CDN servers in China

### ISSUE THREAD

**Issue by accelerator148** [neon-nyan/Collapse#207]
I can't connection server in any cdn in China
cdn id"jsDelier"

**Comment by accelerator148** [comment]
[](url)
[bug.txt](https://github.com/neon-nyan/Collapse/files/12130378/bug.txt)

**Comment by bagusnl** [comment]
Hello~

From the looks of the log it seems that your proxy is having a bit of a tantrum, though can you tell me what you were trying to do to get that exception?

Oh also noted that jsDelivr and Statically is currently deprecated as CDN because they both can't serve any update. Please change to bitbucket or Cloudflare if you are on mainland China

**Comment by bagusnl** [comment]
Closing due to no response from the issue author
