### ISSUE TITLE
Add functions related to Genshin Impact fps unlocking

### ISSUE THREAD

**Issue by Bo-He-J** [neon-nyan/Collapse#214]
I really need this feature to avoid opening unnecessary applications

**Comment by Bo-He-J** [comment]
120fps，144fps，More frame rate settings should be added

**Comment by muscularcandy67** [comment]
Hello, these functions were requested multiple times and all those times we declined adding such features because we would have to directly modify game files, unlike Honkai Impact 3rd and Honkai: Star Rail that just requires modifying registry settings, and it's something we are not committed to do as it would directly violate their ToS. If you want a more specific answer read [here](https://github.com/neon-nyan/Collapse/issues/88#issuecomment-1457422037). You can also check our [contribution guideline](https://github.com/neon-nyan/Collapse/blob/main/CONTRIBUTING.md) to see what we are more likely to add and whatnot.
