### ISSUE TITLE
Include Preview strings in localization files

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#57]
Heyo, opening this because I found some more strings to fix, notably the window that displays the Preview warning notification:

![image](https://user-images.githubusercontent.com/9833218/205836514-bab5d57a-18c7-456b-837c-87fb833f34f6.png)

I was trying to find where the strings were declared in the code as well as in the localization files but could not find any reference to them. Is this part of another library? 

The ideal scenario I had in mind for i18n would be to have all log & rendered elements that contain strings be localized in their respective languages. It is by no means required, but it could simplify the implementation of newer features down the line if all the strings are contained within a subset of files, versus being spread throughout the project.

**Comment by neon-nyan** [comment]
Hi @Cryotechnic,

The string for this notification string is coming from an external notification file located in this link:
https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/blob/main/notification_preview.json

This is supposedly to be localized. But because we can't manage the notification to be localized once it needs to be announced as soon as possible, I've decided to keep it as is.

But I think, we can just move this notification string to localization file instead.
I will take a note for this one.

**Comment by Cryotechnic** [comment]
Sounds good, do you want me to open an issue and fix it by opening a PR on that repo?

**Comment by Cryotechnic** [comment]
Closing this for now as it seems to be resolved.
