### ISSUE TITLE
[Enhancement] Multiple Account Switch Support

### ISSUE THREAD

**Issue by iyungrozy** [neon-nyan/Collapse#65]
EN
it started when a genshin / honkai player had more than 1 account, I hope in the future this quick account change feature will be added

ID
maklum saya punya lebih dari akun makanya dan nyaman sama UInya hehehe

**Comment by Cryotechnic** [comment]
The main issue is that Collapse does not handle authentication inherently, it is simply a launcher into MHY games. That means we would need to implement authentication on the client, which makes no sense since you'd get the prompt again when connecting to MHY servers.

**Comment by neon-nyan** [comment]
### EN
I don't think if it would be applicable since the authentication is being done in-game and not within the launcher.
But I believe it's applicable in some way but it might only causing this launcher on risk to be taken down no longer after that  since it's against miHoYo's DMCA and we are avoiding that.

***

### ID
Saya nggak yakin kalau hal ini bisa diterapkan di launcher karena proses authentikasi cuma bisa terjadi di dalam game dan nggak bisa di dalam launcher.
Saya tahu kalau ada cara untuk pengaplikasian fitur ini. Cuma kemungkinan habis itu, launcher ini bisa saja di-take down oleh miHoYo karena melanggar DMCA mereka dan kita berusaha untuk menghindari hal tersebut.
