### ISSUE TITLE
3.4 genshin update

### ISSUE THREAD

**Issue by ibeez11** [neon-nyan/Collapse#74]
![image](https://user-images.githubusercontent.com/81704406/213065380-d72baff2-eb90-49d8-b3c2-34ef58fbeab2.png)
still happen again after pre-update :)
then what's the point for adding that pre-update too if this happen :)
usually in-game download are around 100mb-1000mb, not this 9000mb :)

**Comment by neon-nyan** [comment]
Hi, sorry for the inconvenience.
We are working on this to fix this bug and hope we can give you an update as soon as possible.

Anyway, do you have some kind of warnings or error while applying the update?

**Comment by ibeez11** [comment]
ah i see, thanks for the update :)

as for bug, no. there's no bug when updating, but after the verifying file,
the launcher ask me to donload 17gb file size again, but it give an option
to download right now or download in-game (forgot to screenshot, sry). so
for that,  chose no because it'll torture me to wait another 17gb download
:)) and then after that, the first pic i sent on the start happen :)

**Comment by bagusnl** [comment]
Would you mind to send the Launcher log file from today?
you can find it by opening Collapse's App Settings>Open App Folder
Then open _logs folder and upload the latest log file there (or the date you tried to update the game and failed.

**Comment by ibeez11** [comment]
Sure, here it is.

**Comment by neon-nyan** [comment]
Hi there,

I've found a suspect of this issue.
Turns out, the old hdiff list file wasn't get deleted and if you've had one, it will be conflicting with the one from 3.4 patch file.

I've pushed a commit that fixed this issue: https://github.com/neon-nyan/Collapse/commit/728ade0472b4edf2fd3d497bfac0ca437bb20167 and this commit has been merged into the new update of this launcher, which is v1.0.55.6.

Please update your launcher to v1.0.55.6 to fix this issue.

For now, I'm going to close this issue as completed and please re-open if you have any issues that need to get attention.
