### ISSUE TITLE
[Question] About converting from steam to pc client.

### ISSUE THREAD

**Issue by sleepymanakete** [neon-nyan/Collapse#82]
Hi!
I'm wondering how will linking my account work after converting from steam to global/pc client? Will I still be logged into the game and I can link my hoyoverse account in-game?

**Comment by neon-nyan** [comment]
Hi @sleepymanakete,
Unfortunately, you can't link your Steam account to HoYoverse account in anyway.
The conversion feature for Steam to Standard Client is intended to be used if you mistakenly download Steam client instead of Standard one and you have HoYoverse account to play with.
This feature doesn't let you to convert your Steam account to be playable with Standard client.

**Comment by sleepymanakete** [comment]
I understand, thank you!
