### ISSUE TITLE
pre-updates fail

### ISSUE THREAD

**Issue by ibeez11** [neon-nyan/Collapse#96]
![image](https://user-images.githubusercontent.com/81704406/230310697-2628c5e4-b9fb-4547-8f52-c916d0387fef.png)
it's been 2times i download this, my internet are stable, but it happen twice. any tips ??

**Comment by Cryotechnic** [comment]
This is a known issue in Collapse due to a bug in the integrity verification functionality of the launcher. This should be fixed in the next major version of Collapse (1.69.0), which should be released to the public in the coming days. 

Apologies with the delays in the response, we've had our hands full with getting the new version ready!

**Comment by Cryotechnic** [comment]
## To provide further clarification on why it is taking so long (a.k.a "The Long Version")

We've discovered an issue in our codebase regarding how we handle game updates for all our currently supported games. While we could issue a temporary fix to mitigate the issue for this version, as we have in the past, we felt that it was better to rethink our approach regarding how we update games as well as perform maintenance (cache updates & game repairs), especially given how we're on the verge of shipping our next major release in over 4 months.

Because of this, we're currently in the middle of rewriting our entire infrastructure for managing game installations. This will allow us to be more efficient as well as future-proof the codebase by applying these changes and consolidating the logic for them into key files which are part of Collapse's codebase. The problem with that, as you are aware, is that Genshin Impact just released their Version 3.6 update, and Honkai Impact 3rd, with Version 6.5. We understand that the timing couldn't have been worse, but due to time constraints, we could not delay working on this rework any further. 

With that being said, we expect the rework to be completed soon and hope to merge that into the main working branch of Collapse, thus shipping version 1.69.0. Thank you for understanding!

**Comment by ibeez11** [comment]
![image](https://user-images.githubusercontent.com/81704406/231349951-e07e6f12-54e7-4f57-991f-39711c367301.png)
thanks for the response, i hope it'll be done as soon as possible, and don't forget to take a rest for ur health :)
onto next question, knowing that genshin too has release 3.6 ver.,, what's the alternative then ??, using original launcher first ? i'm just a afraid that error might pup-up again, and then force it to re-download again, for worst case, if that happen and then make all of the game data corrupt too, it'll be such a high pain for download again genshin data from 0 :((

**Comment by bagusnl** [comment]
@ibeez11 We're sorry for the inconvenience but you currently have to use official launcher for updating purpose. If you haven't pushed the Update Game button, Collapse shouldn't do anything about the game files so it's fine to use original launcher just for updating the game, but you can still use Collapse to launch if you like it that way. I'll attach you the official launcher at the end if you didn't really want to install it.

You just need to extract it then edit the `config.ini` file. Change the `game_install_path` string to be the directory where your Genshin is currently installed, then launch the `launcher.exe` to update the game.
If the official launcher won't recognize the game, temporarily rename your Genshin installation folder to be `Genshin Impact game` and edit the config afterwards.
here's the link to the official launcher archive https://www.mediafire.com/file/21bos5a4zgjv8fi/GI_Official_launcher_v3.6.7z/file

**Comment by Cryotechnic** [comment]
As promised, the next version of Collapse has now shipped (1.69.7). Thus, I am closing this issue.

Thank you for your report!
